name: Test dotfiles install

on: [pull_request, workflow_dispatch]

jobs:
  install-dotfiles-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install chezmoi & dotfiles
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }}
  
  install-dotfiles-macos:
    runs-on: macos-latest
    steps:
      - name: Install chezmoi & dotfiles
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ github.repository_owner }}